version: '3.8'

services:
  hrms:
    build:
      context: .
    container_name: vmis-hrms
    ports:
      - "5566:3000"
    environment:
      - NEXT_PUBLIC_APP_BRAND_PREFIX=VMIS-HRMS
      - NEXT_PUBLIC_API_URL=http://localhost:5566
    restart: unless-stopped
    networks:
      - hrms-network

networks:
  hrms-network:
    driver: bridge
